table IMDB-Movie-Data_Org
	lineageTag: d1e17314-50dc-417a-ac80-86c106a075ab

	measure 'Total Revenue' =
			
			SUM('IMDB-Movie-Data_Org'[Revenue (Millions)])
		lineageTag: cd268f8c-abe2-4975-bbd2-8b9c48f1a25d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: 24aee4c6-39f5-4eca-b8f1-e3f89e09d437
		summarizeBy: none
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 12a5e5e5-9cb6-49f2-9424-76268c010c3c
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Genre
		dataType: string
		lineageTag: d35a29d1-cea0-4eeb-962b-19ebbb2e2837
		summarizeBy: none
		sourceColumn: Genre

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: a1e095bf-a282-43b0-b411-a0b3524c2650
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: 6b5bb140-fe01-4431-b27b-0d0f73af50cb
		summarizeBy: none
		sourceColumn: Director

		annotation SummarizationSetBy = Automatic

	column Actors
		dataType: string
		lineageTag: 3dec1cee-8a6d-44df-9b94-f1434ffeb303
		summarizeBy: none
		sourceColumn: Actors

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5c013a07-baa4-48fa-a649-70dc50616e6c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Runtime (Minutes)'
		dataType: int64
		formatString: 0
		lineageTag: 9fb2f458-1ea4-478d-9a25-b27764419879
		summarizeBy: none
		sourceColumn: Runtime (Minutes)

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: double
		lineageTag: 7102ee89-457d-4f93-93fb-c5aa71d281e2
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Votes
		dataType: int64
		formatString: 0
		lineageTag: aacc532d-a8a4-45eb-8f15-11d3cb58da43
		summarizeBy: none
		sourceColumn: Votes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Revenue (Millions)'
		dataType: double
		lineageTag: daa58401-5082-4fb7-b518-308bf6ac07a4
		summarizeBy: none
		sourceColumn: Revenue (Millions)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Metascore
		dataType: int64
		formatString: 0
		lineageTag: 33d6631f-c4e0-4a5a-bb4c-4d4f1326d71c
		summarizeBy: none
		sourceColumn: Metascore

		annotation SummarizationSetBy = Automatic

	partition IMDB-Movie-Data_Org = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Innomatics\Projects\Power BI\Dataset\IMDB-Movie-Data.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"Rank", Int64.Type}, {"Title", type text}, {"Genre", type text}, {"Description", type text}, {"Director", type text}, {"Actors", type text}, {"Year", Int64.Type}, {"Runtime (Minutes)", Int64.Type}, {"Rating", type number}, {"Votes", Int64.Type}, {"Revenue (Millions)", type number}, {"Metascore", Int64.Type}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

